FROM python:3.11.3

WORKDIR /etl

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./start.sh ./etl/start.sh
COPY ./requirements.txt ./requirements.txt

RUN  pip install --upgrade pip \
     && pip install -r requirements.txt

CMD ["/etl/start.sh"]